<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>

<!DOCTYPE member [
<!ELEMENT member (detail)>
<!ELEMENT detail (id, name_ltname, amount, payment, tell)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name_ltname (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT payment (#PCDATA)>
<!ELEMENT tell (#PCDATA)>
]>

<member>
    <detail>
        <id> CK-C-2000001 </id>
        <name_ltname> Mrs. Isabela Souza </name_ltname>
        <amount> 371 order </amount>
        <payment> Credit Card, PromptPay, Cash </payment>
        <tell> 062-818-4437 </tell>
    </detail>

    <detail>
        <id> CK-C-2100053 </id>
        <name_ltname> Ms. Camila Fernandes </name_ltname>
        <amount> 267 order </amount>
        <payment> Credit Card, Cash </payment>
        <tell> 097-543-1687 </tell>
    </detail>

    <detail>
        <id> CK-C-2100062 </id>
        <name_ltname> Mr. Felipe Pereira </name_ltname>
        <amount> 275 order </amount>
        <payment> Credit Card, PromptPay, Cash </payment>
        <tell> 099-818-6678 </tell>
    </detail>

    <detail>
        <id> CK-C-2300056 </id>
        <name_ltname> Mr. William Davis </name_ltname>
        <amount> 232 order </amount>
        <payment> Credit Card, PromptPay, Cash </payment>
        <tell> 081-173-6478 </tell>
    </detail>

    <detail>
        <id> CK-C-2400027 </id>
        <name_ltname> Ms. Emily Johnson </name_ltname>
        <amount> 72 order </amount>
        <payment> Credit Card, Cash </payment>
        <tell> 098-968-1478 </tell>
    </detail>
</member>